import { build } from 'esbuild';
import { cp, mkdir, readFile, rm, writeFile } from 'node:fs/promises';
import path from 'node:path';
import process from 'node:process';
import { fileURLToPath } from 'node:url';

const root = path.resolve(path.dirname(fileURLToPath(import.meta.url)), '..');
const source = path.join(root, 'app', 'frontend');
const output = path.join(root, 'www');
const release = process.argv.includes('--release');
const apiBaseUrl = String(process.env.GESTORE_API_BASE_URL || '').trim().replace(/\/+$/, '');
const requestedMode = String(process.env.GESTORE_IOS_MODE || '').trim().toLowerCase();
const runtimeMode = requestedMode || (apiBaseUrl ? 'hosted' : 'local');

if (!['local', 'hosted'].includes(runtimeMode)) {
  throw new Error('GESTORE_IOS_MODE must be either "local" or "hosted".');
}

if (apiBaseUrl && !/^https:\/\//i.test(apiBaseUrl) && !/^http:\/\/(localhost|127\.0\.0\.1)(:\d+)?$/i.test(apiBaseUrl)) {
  throw new Error('GESTORE_API_BASE_URL must use HTTPS (localhost is allowed only for development).');
}
if (runtimeMode === 'local' && apiBaseUrl) {
  throw new Error('GESTORE_API_BASE_URL must be empty when GESTORE_IOS_MODE=local.');
}
if (runtimeMode === 'hosted' && !apiBaseUrl) {
  throw new Error('GESTORE_IOS_MODE=hosted requires GESTORE_API_BASE_URL.');
}
if (release && runtimeMode === 'hosted' && !/^https:\/\//i.test(apiBaseUrl)) {
  throw new Error('A hosted release build requires an HTTPS GESTORE_API_BASE_URL.');
}

const resolvedOutput = path.resolve(output);
if (path.dirname(resolvedOutput) !== root || path.basename(resolvedOutput) !== 'www') {
  throw new Error(`Refusing to clean unexpected output directory: ${resolvedOutput}`);
}

await rm(resolvedOutput, { recursive: true, force: true });
await mkdir(resolvedOutput, { recursive: true });
await cp(source, resolvedOutput, { recursive: true });

await writeFile(
  path.join(resolvedOutput, 'js', 'runtime-config.js'),
  `window.GestOreRuntimeConfig = Object.freeze({ apiBaseUrl: ${JSON.stringify(apiBaseUrl)}, mode: ${JSON.stringify(runtimeMode)} });\n`,
  'utf8'
);

await build({
  entryPoints: [path.join(root, 'native', 'native-bridge.ts')],
  outfile: path.join(resolvedOutput, 'js', 'native-bridge.js'),
  bundle: true,
  minify: release,
  sourcemap: release ? false : 'inline',
  format: 'iife',
  platform: 'browser',
  target: ['safari15'],
  banner: { js: '/* GestOre native bridge - generated by tools/build-ios.mjs */' }
});

const indexPath = path.join(resolvedOutput, 'index.html');
const indexHtml = await readFile(indexPath, 'utf8');
if (!indexHtml.includes('js/native-runtime.js')) {
  throw new Error('Native runtime scripts are missing from app/frontend/index.html.');
}

console.log(`iOS web bundle ready: ${path.relative(root, resolvedOutput)}`);
console.log(`Runtime mode: ${runtimeMode}`);
console.log(apiBaseUrl ? `API: ${apiBaseUrl}` : 'API: disabled (device-local data)');
